typography_spectrum: 0.5649307759013027
color:
  brandStrength: 0.7216360066086054
  lightness: 0.2148298746906221
  saturation: 0.5562434780877084
  rhythmicContrast: 0.8614404224790633
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.37513154395855963
name: Edge 4 Consulting
navigation:
  - name: 13 Box
    url: 'http://13boxpresentation.com'
    type: external
  - name: Eugene Moreau
    url: 'http://eugenemoreau.com'
    type: external
  - name: Moreau Communications
    url: 'http://moreaucommunications.com'
    type: external
description: Next Level Business
